# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'mcp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmcp.proto\x12\x08ramen.v1\"\x17\n\x07JsonRpc\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\x32h\n\x03Mcp\x12,\n\x04\x43\x61ll\x12\x11.ramen.v1.JsonRpc\x1a\x11.ramen.v1.JsonRpc\x12\x33\n\x07Session\x12\x11.ramen.v1.JsonRpc\x1a\x11.ramen.v1.JsonRpc(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSONRPC']._serialized_start=23
  _globals['_JSONRPC']._serialized_end=46
  _globals['_MCP']._serialized_start=48
  _globals['_MCP']._serialized_end=152
# @@protoc_insertion_point(module_scope)
